---
title: "sta 250 test"
author: "Yudong Wang"
date: "3/2/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require("knitr")
opts_knit$set(root.dir = "C:/Users/wyd98/Desktop/homework/STA 250/data")
```


```{r}
setwd("C:/Users/wyd98/Desktop/homework/STA 250/data")
library(readxl)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(corrplot)
library(glmnet)
library(fastDummies)
library(caret)
library(MASS)
library(Metrics)
library(stargazer)
```


```{r}
money = read.csv("M2Supply.csv")
cpi_f = read.csv("CPI_Food_in_City.csv")
cpi_f = lead(cpi_f$CPIUFDSL)
cpi_f = na.omit(cpi_f)
econ = money %>% 
  mutate(cpi_f = cpi_f) %>% 
  dplyr::select(-DATE) 

process <- preProcess(econ, method=c("range"))
econ <- predict(process, econ)
```

```{r}
price_trend = read.csv("good_trend.csv")
price_trend = price_trend[-(1:168),]
price_trend = head(price_trend,60)

process <- preProcess(price_trend, method=c("range"))
price_trend <- predict(process, price_trend)

price_data = cbind(price_trend, econ)
price_data2 = price_data %>% dplyr::select(-M2SL)
```

```{r}
write.csv(price_data, "C:/Users/wyd98/Desktop/homework/STA 250/data/price_data.csv", row.names=FALSE)
```


```{r}
bus = read.csv("Busin_and_Indus_trend.csv")
fina = read.csv("Finance_trend.csv")
gov = read.csv("Law_and_Gov_trend.csv")
health = read.csv("Health_trend.csv")
travel = read.csv("Travel_trend.csv")
aggre_trend = bus %>% 
  mutate(finance = fina$Finance) %>% 
  mutate(gov = gov$Law_and_Gov) %>% 
  mutate(health = health$Health) %>% 
  mutate(travel = travel$Travel) %>% 
  filter(index < "2023-01-01") %>% 
  dplyr::select(-index)

econ_new = tail(econ, -2)
aggre_data = cbind(aggre_trend, econ_new)

process <- preProcess(aggre_data, method=c("range"))
aggre_data <- predict(process, aggre_data)
```

```{r}
econ_lm = lm(cpi_f~., econ)
summary(econ_lm)
```



```{r}
price_lm = lm(cpi_f~., price_data)
summary(price_lm)
```

```{r}
price2_lm = lm(cpi_f~., price_data2)
summary(price2_lm)
stargazer(econ_lm, price_lm, price2_lm,
          econ_ni_lm, price_ni_lm, price2_ni_lm, 
          type = "html", out = "us1.html")
```

```{r}
aggre_lm = lm(cpi_f~., aggre_data)
summary(aggre_lm)
```

```{r}
full_model = lm(cpi_f~., price_data)
step_good = stepAIC(full_model, direction = "both", trace = F)
summary(step_good)
```

```{r}
full_model = lm(cpi_f~., price_data2)
step_good = stepAIC(full_model, direction = "both", trace = F)
summary(step_good)
```

```{r}
full_model = lm(log(cpi_f+1)~., price_data)
step_good = stepAIC(full_model, direction = "both", trace = F)
summary(step_good)
```

```{r}
full_model = lm(log(cpi_f+1)~., price_data2)
step_good = stepAIC(full_model, direction = "both", trace = F)
summary(step_good)

```

```{r}
# only money supply
acc = c()
for (i in 1:100){
  n = sample(nrow(econ), 0.8*nrow(econ), replace = F, prob = NULL)
  train = econ[n, ]
  test = econ[-n,]
  full_model = lm(cpi_f~., train)
  step_good = stepAIC(full_model, direction = "both", trace = F)
  pred = predict(step_good, test)
  temp = R2(pred, test$cpi_f)
  acc = append(acc, temp)
}
mean(acc)
```

```{r}
# all variables stepwise
acc = c()
for (i in 1:100){
  n = sample(nrow(price_data), 0.8*nrow(price_data), replace = F, prob = NULL)
  train = price_data[n, ]
  test = price_data[-n,]
  full_model = lm(cpi_f~., train)
  step_good = stepAIC(full_model, direction = "both", trace = F)
  pred = predict(step_good, test)
  temp = R2(pred, test$cpi_f)
  acc = append(acc, temp)
}
mean(acc)
```

```{r}
# only trend variables stepwise
acc = c()
for (i in 1:100){
  n = sample(nrow(price_data2), 0.8*nrow(price_data2), replace = F, prob = NULL)
  train = price_data2[n, ]
  test = price_data2[-n,]
  full_model = lm(cpi_f~., train)
  step_good = stepAIC(full_model, direction = "both", trace = F)
  pred = predict(step_good, test)
  temp = R2(pred, test$cpi_f)
  acc = append(acc, temp)
}
mean(acc)
```


```{r}
# all variables LASSO
acc = c()
for (i in 1:100){

  n = sample(nrow(price_data), 0.8*nrow(price_data), replace = F, prob = NULL)
  train = price_data[n, ]
  test = price_data[-n,]

  x_train = as.matrix(train %>% dplyr::select(-cpi_f))
  y_train = train$cpi_f

  x_test = as.matrix(test %>% dplyr::select(-cpi_f))
  y_test = test$cpi_f


  lambdas = 10^seq(2,-3, by = -0.1)

  lasso = cv.glmnet(x_train, y_train, alpha = 1, lambda = lambdas, nfold = 5, standardize = T)
  lambda_best = lasso$lambda.min
  lasso = glmnet(x_train, y_train, alpha = 1, lambda = lambda_best, standardize = T)

  pred_train = predict(lasso, s = lambda_best, newx = x_train)
  tr_acc = 1- sum((pred_train - y_train)^2) / sum((y_train - mean(y_train))^2)

  pred_test = predict(lasso, s = lambda_best, newx = x_test)
  temp = R2(pred_test, y_test)
  acc = append(acc, temp)
}
mean(acc)
```

```{r}
# only trend variables LASSO
acc = c()
for (i in 1:100){

  n = sample(nrow(price_data2), 0.8*nrow(price_data2), replace = F, prob = NULL)
  train = price_data2[n, ]
  test = price_data2[-n,]

  x_train = as.matrix(train %>% dplyr::select(-cpi_f))
  y_train = train$cpi_f

  x_test = as.matrix(test %>% dplyr::select(-cpi_f))
  y_test = test$cpi_f


  lambdas = 10^seq(2,-3, by = -0.1)

  lasso = cv.glmnet(x_train, y_train, alpha = 1, lambda = lambdas, nfold = 5, standardize = T)
  lambda_best = lasso$lambda.min
  lasso = glmnet(x_train, y_train, alpha = 1, lambda = lambda_best, standardize = T)

  pred_train = predict(lasso, s = lambda_best, newx = x_train)
  tr_acc = 1- sum((pred_train - y_train)^2) / sum((y_train - mean(y_train))^2)

  pred_test = predict(lasso, s = lambda_best, newx = x_test)
  temp = R2(pred_test, y_test)
  acc = append(acc, temp)
}
mean(acc)
```

```{r}
library(caret)
```


```{r}
# all variables 10-fold CV
tr_control = trainControl(method = "cv", number = 10)
model = train(cpi_f~., data = price_data, method = "lm", trControl = tr_control)
print(model)
```


```{r}
# only trend variables 10-fold CV
tr_control = trainControl(method = "cv", number = 10)
model = train(cpi_f~., data = price_data2, method = "lm", trControl = tr_control)
print(model)
```

```{r}
n = sample(nrow(econ), 0.8*nrow(econ), replace = F, prob = NULL)
train = price_data[n, ]
test = price_data[-n,]
  
train2 = price_data2[n, ]
test2 = price_data2[-n,]

train_e = econ[n,]
test_e = econ[-n,]
```

```{r}
# only money supply 10-fold CV
tr_control = trainControl(method = "cv", number = 10)
model = train(cpi_f~., data = train_e, method = "lm", trControl = tr_control)
print(model)

pred = predict(model, test_e)
R2(pred, test_e$cpi_f)
```

```{r}
# Money + trend variables 10-fold CV
tr_control = trainControl(method = "cv", number = 10)
model_f = train(cpi_f~., data = train, method = "lm", trControl = tr_control)
print(model_f)

pred_f = predict(model_f, test)
R2(pred_f, test$cpi_f)
```

```{r}
# only trend variables 10-fold CV
tr_control = trainControl(method = "cv", number = 10)
model = train(cpi_f~., data = train2, method = "lm", trControl = tr_control)
print(model)

pred = predict(model, test2)
R2(pred, test2$cpi_f)
```

```{r}
plot(test$cpi_f)
lines(pred_f, col = "2")
lines(pred, col = "4")
```


```{r}
pred_e = predict(econ_lm, test_e)
  
colors = c("Baseline" = "tomato", "M2+Google" = "yellowgreen", "Google only" = "greenyellow", "real CPI" = "black")

us_pic = ggplot(test, aes(x = c(1:12)))
us_pic + geom_point(aes(y = cpi_f, col = "real CPI")) +
  geom_line(aes(y = pred_e, col = "Baseline")) +
  geom_line(aes(y = pred, col = "Google only")) +
  geom_line(aes(y = pred_f, col = "M2+Google")) +
  labs(x = "X_i", y = "CPI") + xlim(0,13)
```





